apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: mysqldata
  name: mysqldata
spec:
  storageClassName: mysqldata-ssd
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
status: {}

--- 
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mysqldata-ssd
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2


 
